about/urls.py
from django.urls import path

from . import views

app_name = "about"


urlpatterns = [
    path('', views.all_about, name='all_about'),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from portfolio import views



urlpatterns = [
    path('', views.home, name='homeporfolio'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('todo/', include('todo.urls')),
    path('film/', include('film.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.db import models

class Project(models.Model):
     title = models.CharField(max_length=100)
     description = models.CharField(max_length=250)
     image = models.ImageField(upload_to='portfolio/images/')
     url = models.URLField(blank=True)

     def __str__(self):
          return self.title

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="ar" dir="ltr" xmlns="http://www.w3.org/1999/html">

<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.rtl.min.css"
          integrity="sha384-dc2NSrAXbAkjrdm9IYrX10fQq9SDG6Vjz7nQVKdKcJl3pC+k37e7qJR5MVSCS+wR" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link rel="shortcut icon" type="image/png" href="{% static 'todo/logo.png' %}">
    <title>ZiCode</title>
</head>


<body>

<nav class="navbar navbar-main navbar-expand-lg navbar-dark bg-primary" id="navbar-main">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav px-1 my-lg-2">
            <li class="nav-item">
                <a class="navbar-brand" href="{% url 'homeporfolio' %}">
                    <img src="{% static 'portfolio/zicode.png' %}" alt="Zicode" style="height: 50px;">
                </a>
            </li>
        </ul>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mt-2 px-1">

                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'blog:all_blogs' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'listfilms' %}">List of films</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about:all_about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% static 'portfolio/literature.jpg' %}"
                       target="_blank">Literature</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" target="_blank"
                       href="{% static 'portfolio/Resume z.pdf' %} ">Resume</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" target="_blank" href="https://t.me/odin_v_odnogo">Telegram
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                             class="bi bi-telegram" viewBox="0 0 16 16">
                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
                        </svg>
                    </a>
                </li>

                <form class="d-flex" role="search" action="{% url 'blog:all_blogs' %}">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                           name="search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>


                {% if user.is_authenticated %}

                <div class="mt-3 mx-4 collapse navbar-collapse position-absolute top-0 start-0">


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'currenttodos' %}">
                            <u>Currentusername: "{{ user.username }}"</u>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'createtodo' %}">Create</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'currenttodos' %}">Current</a>
                    </li>
                    <li>
                        <a class="nav-link" style="text-align: right;" href="{% url 'completedtodos' %}">Completed</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
                        <form style='display: none;' method="POST" action="{% url 'logoutuserr' %}">
                            {% csrf_token %}
                            <button id="signOutBtn" type="submit">Logout</button>
                        </form>
                    </li>
            </ul>


            {% else %}
            <div class="mt-3 mx-4 collapse navbar-collapse position-absolute top-0 start-0">

                <ul class="navbar-nav mr-0 ml-auto">

                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signupuser' %}">Sign Up</a>
                    </li>
                </ul>
            </div>
            {% endif %}

            </ul>
        </div>
    </div>
</nav>


</body>
</html>

{% block todo %}{% endblock %}


{% block content %}
Hello my Friend's
{% endblock %}

{% block content_film %}{% endblock %}

{% block admin-panel %}
<div class="admin-panel">
    <a href="/admin" class="btn btn-outline-info" target="_blank">Admin</a>
</div>
{% endblock %}


<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
-->

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}


{% load static %}


<div class="bg-primary">
    <figure class="text-center">
        <blockquote class="blockquote">
            <h1 class="display-2">Welcome to my business card website.</h1>
        </blockquote>
    </figure>

    <div class="row justify-content-around bg-dark text-secondary">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 col-sm-12">
                    <img class="w-100" src="{%static 'portfolio/mountain.jpg' %}" class="img-thumbnail"
                         alt="Сопроводительная надпись для изображения">
                </div>
                <div class="col-xl-6 col-sm-12">
                    <h1 class="my-3">Текст взят с: <span class="badge bg-secondary">Lorem Ipsum</span></h1>
                    <p>Praesent neque orci, placerat vitae tincidunt eget, venenatis nec dolor. Aenean sed nibh enim.
                        Integer at purus tellus. Phasellus convallis est sit amet finibus efficitur. Etiam vitae
                        lobortis ante. In hac habitasse platea dictumst. Vivamus a sapien tempus, rhoncus ligula quis,
                        fermentum sapien. Suspendisse rhoncus luctus lobortis. Aliquam erat volutpat. Pellentesque
                        turpis sem, tristique vel ullamcorper aliquet, vulputate nec lorem. Morbi non lacinia odio, in
                        interdum eros. Maecenas vel dapibus quam, nec mollis libero. Cras id est a nibh euismod viverra.
                        Curabitur auctor dignissim arcu eu finibus.</p>
                    <p>Suspendisse euismod convallis fermentum. Pellentesque sed luctus sapien. Cras sodales condimentum
                        augue, placerat dignissim nibh placerat eu. Nam tincidunt, tellus sit amet faucibus consequat,
                        lacus tellus dignissim mauris, eu ornare diam nisi id nulla. Nunc augue felis, bibendum eget
                        turpis in, semper rutrum tellus. Sed at condimentum est. Nulla facilisi. Aenean feugiat ipsum ut
                        sem imperdiet malesuada. Aenean id sapien est. Interdum et malesuada fames ac ante ipsum primis
                        in faucibus. Cras nibh erat, posuere tincidunt nisi at, pulvinar sodales augue.
                </div>
            </div>
        </div>

        <h2 class="text-center">My project in GitHub</h2>
        <div class="container">
            <div class="mx-auto" style="width: 600px;">
                <div class="row gy-3">
                    <div class="text-center">
                        {% for project in projects %}
                        {% if project.url %}
                        <a href="{{ project.url }}">
                            <div class="card mb-4 shadow-sm">
                                <img src="{{ project.image.url }}" width="100%">
                                <div class="card-body bg-primary text-black">
                                    <h5 class="col-sm-12"><em>{{ project.title }}</em></h5>
                                    <p class="card-text">{{ project.description }}</p>
                                </div>
                            </div>
                        </a>

                        {% endif %}

                        {% endfor %}
                    </div>
                </div>
            </div>

            {% endblock %}