blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from portfolio import views



urlpatterns = [
    path('', views.home, name='homeporfolio'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('todo/', include('todo.urls')),
    path('film/', include('film.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=105)
    description = models.CharField(max_length=250)
    date = models.DateField()
    image = models.ImageField(upload_to='blog/images/')

    def __str__(self):
        return self.title

blog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Blog

from django.db.models import Q


def all_blogs(request):
    search_query = request.GET.get('search', '')
    if search_query:
        blogs = Blog.objects.filter(Q(title__icontains=search_query) | Q(description__icontains=search_query))
    else:
        blogs = Blog.objects.all()

    paginator = Paginator(blogs, 2)

    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    is_paginated = page.has_other_pages()

    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    context = {
        'page_object': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url
    }
    return render(request, 'blog/all_blogs.html', context)


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

<div class="text-center">
    <h2>Sergey writen blogs </h2>
</div>


<div class="container">
    <div class="row">
        {% for blog in page_object.object_list %}

        {% if forloop.counter|divisibleby:"2" %}
        <div class="col-6">
            {% else %}
            <div class="col-6">
                {% endif %}


                <a href="{% url 'blog:detail' blog.id %}">
                    <div class="card mb-4 shadow-sm">
                        <img src="{{ blog.image.url }}" class="card-img-top img-fluid">
                        <div class="card-body text-center">
                            <h5> {{ blog.date|date:'M d Y'|upper}}</h5>
                            <p> {{ blog.description|striptags|truncatechars:20}}</p>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="position-absolute top-100 start-50 translate-middle">
        {% if is_paginated %}

        <nav aria-label="...">
            <ul class="pagination">
                <li class="page-item {% if not prev_url %} disabled {% endif %}">
                    <a class="page-link" href="{{ prev_url }}" tabindex="-1">Previous</a>
                </li>


                {% for n in page_object.paginator.page_range %}

                {% if page_object.number == n %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ n }}">
                        {{ n }} <span class="sr-only"></span></a>
                </li>
                {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}

                <li class="page-item">
                    <a class="page-link" href="?page={{ n }}">{{ n }}</a>
                </li>
                {% endif %}
                {% endfor %}
                <li class="page-item {% if not next_url %} disabled {% endif %}">
                    <a class="page-link" href="{{ next_url }}" tabindex="-1">Next</a>
                </li>

            </ul>
        </nav>
        {% endif %}
    </div>
    {% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
{{ block.super }}
<div class="col-md-55 text-center">

    <h1>{{ blog.title }}</h1>


    <h2>-- {{ blog.date|date:'F jS Y' }}--</h2>


    {{ blog.description|safe }}


    {% endblock %}